enum Categoria {
  NENHUM,  NFE,  CTE,  MDFE,  NFCE,  EFD,  CTEOS,  DIEF,  GIA_ST,
  CONV_115,  BPE,  PGDASD,  TEF,  DEFIS,  NFE_EVENTO,  CTE_EVENTO,
  MDFE_EVENTO,  NFCE_EVENTO,  EFD_OIE,  SCANC,  DI,  CCC,  DESTDA  }